### ISSUE TITLE
Избавиться от неиспользуемых импортов

### ISSUE THREAD

**Issue by umpteenthdev** [CasperKHV/WeatherProjectAndroidStudio#5]
### Шаги
- [x] Посмотреть [видео про оптимизацию импортов](https://www.jetbrains.com/guide/java/tips/optimize-imports/#:~:text=Optimize%20Imports%20using%20the%20shortcut,Optimize%20imports%20on%20the%20fly.)
- [x] Сделать новую ветку для новой задачи
- [x] Зайти в MainActivity и оптимизировать импорты
- [x] Сделать коммит с осмысленным сообщением
- [x] Пушнуть ветку на github
- [x] Посмотреть [видео про автоматическое форматирование кода](https://www.jetbrains.com/guide/java/tips/reformat-code/)
- [x] Зайти в MainActivity и применить автоформатирование
- [x] Сделать коммит
- [x] Пушнуть ветку на github
- [x] Выделить все классы проекта в дереве проекта и кликнуть комбинацию автоформатирования. Применить автоформатирование и оптимизацию импортов ко всем классам сразу через появившееся окно
- [x] Коммит, пуш
- [x] Создать PR в master
- [x] #7
- [x] #8
- [x] После ревью смержить PR
- [ ] Закрыть issue

**Comment by umpteenthdev** [comment]
@CasperKHV, по поводу пункта `Прикрепить PR к этой issue`. Ты создал новую issue вместо этого. Этого делать не нужно было. PR - это pull request. Здесь они крепятся справа в блоке `Development`. 

По поводу комментария. Не надо для комментария новую issue заводить. В нашем случае issue - аналог задачи. Часто это сообщение о баге или вопрос от внешнего пользователя. Комментарий нужно написать ниже, тут есть кнопка и поле ввода.

Остальные пункты, если они сделаны, нужно пометить галочкой. Если нет - сделать и пометить. Конвертировать пункты в issue будем позже, когда начнем большие задачи делать.

**Comment by CasperKHV** [comment]
@umpteenthdev комментарий в нужном месте.
